

/* GPIO */

const GPIO_MODER_IN = 0b00
const GPIO_MODER_OUT = 0b01
const GPIO_MODER_ALT = 0b10
const GPIO_MODER_ANA = 0b11

const GPIO_PUPDR_NO = 0b00
const GPIO_PUPDR_PU = 0b01
const GPIO_PUPDR_PD = 0b10

/* GPIOA */
const GPIOA_BASE = 0x40020000 + 0*0x400
reg GPIOA_MODER @ GPIOA_BASE + 0x00
reg GPIOA_OTYPER @ GPIOA_BASE + 0x04
reg GPIOA_OSPEEDR @ GPIOA_BASE + 0x08
reg GPIOA_PUPDR @ GPIOA_BASE + 0x0c
reg GPIOA_IDR @ GPIOA_BASE + 0x10
reg GPIOA_ODR @ GPIOA_BASE + 0x14
reg GPIOA_BSRR @ GPIOA_BASE + 0x18

/* GPIOD */
const GPIOD_BASE = 0x40020000 + 4*0x400
reg GPIOD_MODER @ GPIOD_BASE + 0x00
reg GPIOD_OTYPER @ GPIOD_BASE + 0x04
reg GPIOD_OSPEEDR @ GPIOD_BASE + 0x08
reg GPIOD_PUPDR @ GPIOD_BASE + 0x0c
reg GPIOD_IDR @ GPIOD_BASE + 0x10
reg GPIOD_ODR @ GPIOD_BASE + 0x14
reg GPIOD_BSRR @ GPIOD_BASE + 0x18

/* configuration */
const USER_BUT = 0
const GREEN_LED = 12
sig BUTTON @ GPIOA_IDR[USER_BUT]


/* automaton */
auto A

	GPIOD_MODER[2*GREEN_LED+1 .. 2*GREEN_LED] = GPIO_MODER_OUT
	GPIOA_MODER[2*USER_BUT+1 .. 2*USER_BUT] = GPIO_MODER_IN
	GPIOA_OTYPER[2*USER_BUT+1 .. 2*USER_BUT] = GPIO_PUPDR_PD

	state up:
		GPIOD_BSRR[GREEN_LED + 16] = 1
		when BUTTON:
			goto down

	state down:
		GPIOD_BSRR[GREEN_LED] = 1
		when !BUTTON:
			goto up

